### ISSUE TITLE
InputEvent* misleading

### ISSUE THREAD

**Issue by burstina** [Federico-Ciuffardi/Godot-Touch-Input-Manager#1]
ciao,
vedo che sei italiano quindi bentrovato!
Vedo che usi oggetti che chiami "InputEvent*", ma in realtà non sono oggetti compatibili con la classe `InputEvent `dell'engine in quanto di fatto utilizzi segnali e non eventi.
Per quanto è vero che un nome è sempre e solo un nome, nella pratica è altamente fuorviante, perchè viene automatico pensare di scrivere in _input(event) `if event is InputEventScreenPinch:` che non funzionerà mai.
Consiglio di cambiare nomi a questi oggetti, al fine di mantenere chiarezza e linearità con il resto dell'engine.

ciao

**Comment by Federico-Ciuffardi** [comment]
Hi!

I don't speak Italian (only English and Spanish) but I used a translator, so it's fine.

I agree with you, but instead of changing the names, I thought about improving the current implementation so that it also triggers `_input `.

What do you think?

Regards.

**Comment by burstina** [comment]
ouch, sorry, your name is so italian 😄 
Triggering `_input ` should be really great.
It is a pain though for a lot of reasons and limitations. I experienced them myself coding [SwipeEvent](https://github.com/burstina/SwipeEvent) putting max effort in compatibility and ease of use, nevertheless this asset has still some quirks and put  coders to use _cum grano salis_.

I can assure you however, codinig SwipeEvent was a loot of fun though. 😃
