### ISSUE TITLE
Condition "!is_visible_in_tree()" is true

### ISSUE THREAD

**Issue by dbrova15** [Federico-Ciuffardi/Godot-Touch-Input-Manager#10]
I add player control to the already prepared scene using your plugin. The player doesn't move and I get an error:

E 0:00:02.469   _input: Condition "!is_visible_in_tree()" is true.
  <C++ Source>  scene/2d/touch_screen_button.cpp:201 @ _input()

![изображение](https://user-images.githubusercontent.com/20703983/93767362-99572680-fc20-11ea-9d3b-041244d067d8.png)

If I remove everything from the tree except the player, then there is no error and he moves.
What am I doing wrong?

**Comment by Federico-Ciuffardi** [comment]
The error message makes me think that maybe the plugin isn't the cause the error.

So first check out if something on [this](https://www.reddit.com/r/godot/comments/aemh69/hello_what_this_error_means) thread makes sense in your case (I just see that the user posting has a similar error and it go fixed.

If the error persist, tell me about how did you set up the plugin. And how are you using it. As I will need this information to help you.
