### ISSUE TITLE
Bad download hash

### ISSUE THREAD

**Issue by sporeservant** [Federico-Ciuffardi/Godot-Touch-Input-Manager#3]
hey there - I went to load this asset in Godot 3.2 and got the following error:

Asset Download Error
Bad download hash, assuming file has been tampered with.

![Screen Shot 2020-03-25 at 10 21 12 PM](https://user-images.githubusercontent.com/37244145/77603677-13fbef00-6ee7-11ea-861e-ab4c74b9315c.png)

**Comment by Federico-Ciuffardi** [comment]
Hi, thank you for this letting me know. I just tried  and the same happened to me suppose this is an error of some sort, I will try to get it fixed, but in the meantime you can download the release directory with this link [https://github.com/Federico-Ciuffardi/Godot-Touch-Input-Manager/releases/download/v0.5.3/Godot-Touch-Input-Manager.zip](https://github.com/Federico-Ciuffardi/Godot-Touch-Input-Manager/releases/download/v0.5.3/Godot-Touch-Input-Manager.zip)

**Comment by Federico-Ciuffardi** [comment]
Looks like this is an issue of the Godot Asset Library [https://github.com/godotengine/godot-asset-library/issues/207](https://github.com/godotengine/godot-asset-library/issues/207).

**Comment by Federico-Ciuffardi** [comment]
Fixed!
