### ISSUE TITLE
Pinch not working when over buttons. 

### ISSUE THREAD

**Issue by shafnaz** [Federico-Ciuffardi/Godot-Touch-Input-Manager#8]
Hello developers,

![image](https://user-images.githubusercontent.com/37254287/79075543-e32efe80-7cc9-11ea-97d4-f17d9e8aa404.png)
This image above is a map with buttons on them.
There seems to be an issue when pinching over these buttons.

There is an option for "mouse filter". This is useful when using a ScrollContainer containing buttons . ScrollContainer also has a "deadzone" to avoid touching and dragging issues over buttons.
Looking into these can help solve the problem.

Great work on the Plugin!

**Comment by Federico-Ciuffardi** [comment]
Does the mouse filter option not work? The documentation mentions that it should ignore touch events as well.

> Set mouse_filter to MOUSE_FILTER_IGNORE to tell a Control node to ignore mouse or touch events. You’ll need it if you place an icon on top of a button.

**Comment by shafnaz** [comment]
Filtering works, but with extra code. What I did is have timeout change the filter to MOUSE_FILTER_IGNORE after 0.2sec. from MOUSE_FILTER_STOP at touch.pressed. That's how I solved it.

If it's on MOUSE_FILTER_IGNORE, then I can't press the buttons.
If it's on the other filters, then pinching still gets blocked. As you see in the gif below, i'm mouse wheel zooming in and out on the button, which doesn't work; around the button does. I checked it on mobile phone as well.
I also noticed that when dragging on a button, the button still gets pressed on release.
Hope this info helps.

![issueTouch2](https://user-images.githubusercontent.com/37254287/79188449-65681180-7df5-11ea-8a1e-40fbb359283b.gif)

**Comment by Federico-Ciuffardi** [comment]
I'm almost sure that using the mouse filter option is the intended (and best)  way of handling these interactions with Control Nodes that handles inputs.

For the button pressing on the end of a drag you should change the behavior of the button to only get pressed on a tap (not just on release). Try using the [InputEventSingleScreenTap](https://github.com/Federico-Ciuffardi/Godot-Touch-Input-Manager#inputeventsinglescreentap)
