### ISSUE TITLE
Method for detecting swipe release

### ISSUE THREAD

**Issue by daybreakclay** [Federico-Ciuffardi/Godot-Touch-Input-Manager#9]
Hey, have you worked out a way to detect when a swipe has ended? Is there a way to use is_action_just_released with InputEventSingleScreenDrag?

I've been trying to hack something together for a few days no with no luck, so I thought I'd see if it's something you'd already solved.

Thanks for your code base.

**Comment by Federico-Ciuffardi** [comment]
> Hey, have you worked out a way to detect when a swipe has ended? 

No, I haven't but I think it would be great to add a `InputEventScreenSwipe`.

 > Is there a way to use is_action_just_released with InputEventSingleScreenDrag?

I think so, try to detect when the last touch is released. Or when a `InputEventSingleScreenDrag` stops for a certain amount of time.

I was thinking for the next addition to be a `InputEventScreenSwipe` but right now I am busy with my studies. If you manage to get the swipe working let me know so I can use it when I get into it myself, or even better, try to open a PR.

**Comment by Federico-Ciuffardi** [comment]
Single and multiple finger swipes are included in GDTIM 2.0.0-beta.
